#!/bin/bash

# check for required packages
for pkg in composer php php-cli php-xml mysql-server mysql-client
do
    if ! dpkg -s $pkg | grep -q "Status: install ok installed"
    then
	PKG+=("$pkg") 
    fi
done

# install missing packages
if [ ${#PKG[@]} -gt 0 ]
then
    if ! sudo apt install -y "${PKG[@]}"
    then
	echo "some required ubuntu packages (${PKG[@]}) failed to install"
	exit 1
    fi
fi

# create quickstart
if [ ! -d quickstart ]
then
   composer create-project laravel/laravel quickstart --prefer-dist
fi

# bash function to create random 256 bit key as 64 characters that
# include lower case, upper case, numbers, and special characters.
# it takes 1024 random bytes from the os, passes it through a sha256
# hash, then "leet" translates the result.  The last step does not
# add any entropy, but it lets the key pass the mysql requirements
# for a password (upper, lower, numeric and symbol)
function key256 () {
    dd bs=1024 count=1 if=/dev/random | sha256sum | cut --delimiter=' ' --fields=1 | sed 's/a/@/g;s/b/!/g;s/1/I/g;s/0/O/g'
}

cd quickstart

# setup database if it has not been setup before
if egrep -q "^DB_PASSWORD=$" .env
then
   DB_NAME=laravel-quickstart-db
   DB_USER=laravel-quickstart-user
   DB_PASS="$(key256)"
   sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;
DROP USER IF EXISTS '$DB_USER'@'localhost';
CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON \`$DB_NAME\`.*
TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
SQL
  sed -i- -e "s/^DB_DATABASE=.*$/DB_DATABASE='$DB_NAME'/" \
         -e "s/^DB_USERNAME=.*$/DB_USERNAME='$DB_USER'/" \
         -e "s/^DB_PASSWORD=.*$/DB_PASSWORD='$DB_PASS'/" .env
fi
